version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
endrem = true
magnumtorch = true
bedspreads = true
resource_nether_ores = true
excavated_variants = true
quartzelv = true
storagedrawers = true
sawmill = true
hoppergadgetry = true
easyanvils = true
enderchests = true
minecraft = true
lootr = true
mythicupgrades = true
fwaystones = true
comforts = true
plushie_buddies = true
animal_pen = true
handcrafted = true
ftbquests = true
universal_graves = true
bushierflowers = true
illagerinvasion = true
toms_storage = true
reinfchest = true
