toggleEffectsStatus = false
colorMode = "Effect"
toggleMovementStatus = false
toggleEquipmentStatus = true

[uiConfig]
toggleSimpleHUDEnhanced = true
textColor = 16777215
textBackground = true
textScale = 100
textAlignment = "Left"

[statusElements]
Xcords = 0
Ycords = 0
toggleLightLevel = false
togglePlayerName = false
togglePing = true
toggleTPS = false
toggleServerName = false
toggleServerAddress = false

[statusElements.coordinates]
toggleCoordinates = false
toggleDirection = true
toggleOffset = true
toggleNetherCoordinateConversion = false
toggleChunkCoordinates = false
toggleSubChunkCoordinates = false

[statusElements.fps]
toggleFPS = true
toggleColourFPS = false

[statusElements.playerSpeed]
togglePlayerSpeed = false
togglePlayerVerticalSpeed = false

[statusElements.Biome]
toggleBiome = false
toggleBiomeLabel = false

[statusElements.gameTime]
toggleGameTime = true
toggleGameTime24Hour = true
toggleGameDayCounter = false

[statusElements.systemTime]
toggleSystemTime = true
textScale = 100
textBackground = false
toggleSystemTime24Hour = true

[statusElements.counters]
toggleEntityCount = false
toggleParticleCount = false

[statusElements.counters.chunkCount]
toggleChunkCount = false
toggleTotal = true
toggleLoaded = true

[effectsStatus]
backgroundColor = -2147483648
beneficialForegroundColor = -2130706433
harmfulForegroundColor = -2130706433
neutralForegroundColor = -2130706433

[movementStatus]
toggleMovementStatus = false
textScale = 100
movementStatusLocationX = 0
movementStatusLocationY = 90

[movementStatus.movementTypes]
toggleSprintStatus = true
toggleSneakStatus = true
toggleFlyingStatus = true
toggleSwimmingStatus = true

[paperDoll]
togglePaperDoll = true
togglePaperDollTimer = true
paperDollTimeOut = 3000
textScale = 100
paperDollLocationX = 100
paperDollLocationY = 0

[equipmentStatus]
showCount = false
showNonTools = true
textScale = 100
equipmentOrientation = "Vertical"
equipmentAlignment = "Auto"
equipmentStatusLocationX = 100
equipmentStatusLocationY = 50

[equipmentStatus.Durability]
showDurability = false
showTotalCount = false
showDurabilityAsPercentage = false
showColour = true
showDurabilityAsBar = true

[equipmentStatus.Durability.slots]
Head = true
Body = true
Legs = true
Boots = true
OffHand = true
MainHand = true

[equipmentStatus.slots]
Head = true
Body = true
Legs = true
Boots = true
OffHand = false
MainHand = false
